#!/bin/bash

CHROME_USER="chrome"
CHROME_HOME="/home/${CHROME_USER}"
chmod 755 /var/lib/ybs32/bin/*

# Create chrome user
if ! id -u chrome &>/dev/null; then
    useradd -m -s /bin/bash ${CHROME_USER}
    usermod -aG audio ${CHROME_USER}
fi

# Configure xserver
echo "xhost local:chrome" > ${CHROME_HOME}/.xinitrc
echo "su chrome -p -c 'cd ${CHROME_HOME}; USER=${CHROME_USER} HOME=${CHROME_HOME} startfluxbox'" >> /home/chrome/.xinitrc

# Configure fluxbox
mkdir -p ${CHROME_HOME}/.fluxbox
chown -R chrome:chrome ${CHROME_HOME}/.fluxbox

# Set static ip address
/var/lib/ybs32/bin/static_ip

# Enable service
systemctl daemon-reload
systemctl enable deploy
systemctl enable xserver
systemctl enable pulseaudio