{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "planet.serviceAccountName" . }}
  labels:
{{ include "planet.labels" . | nindent 4 }}
{{- end -}}
